[style.description]
foreground = "purple"
underline = false
bold = false

[style.command_name]
foreground = "blue"
underline = false
bold = true

[style.example_text]
foreground = "green"
underline = false
bold = false

[style.example_code]
foreground = "blue"
underline = false
bold = true

[style.example_variable]
foreground = "yellow"
underline = false
bold = false

[display]
compact = false
use_pager = false

[updates]
auto_update = true
auto_update_interval_hours = 72
